### ISSUE TITLE
add react-timer-mixin to package.json

### ISSUE THREAD

**Issue by olegsmetanin** [bgrieder/RNTSExplorer#1]
uncaught error Error: UnableToResolveError: Unable to resolve module react-timer-mixin from /Volumes/DATA/SOA/2015/github/RNTSExplorer/gen/components/ActivityIndicatorIOSExample.js: Invalid directory /Volumes/node_modules/react-timer-mixin

**Comment by bgrieder** [comment]
Thanks. Fix committed
