### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by mrpatiwi** [bgrieder/RNTSExplorer#2]
When I try:
```typescript
// .tsx
/// <reference path="../typings/tsd.d.ts"/>

'use strict'

import React from 'react-native'
const {
  Text,
  View,
  Component,
} = React;
```

The generated file looks like:
```js
// .js
'use strict';
var react_native_1 = require('react-native');
const { Text, View, Component, } = react_native_1.default;
```

And produces a error because of `default` begin used.

When I try the same but without `import`:
```typescript
// .tsx
const React = require("react-native");
const {
  Text,
  View,
  Component,
} = React;
```
```js
// .js
'use strict';
const React = require("react-native");
const { Text, View, Component, } = React;
```

It's working but I lost typings and my IDE complains. 

Is the definition file `react-native.d.ts` correct?

**Comment by bgrieder** [comment]
Are you using ES6 as a target ? You should be getting ES6 syntax (e.g. no `require`):

    'use strict';
    import React from 'react-native';
    const { Image, StyleSheet, Text, View, } = React;


If you are using ES5 try `import React = require('react-native')` (untested)
